name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - uses: arduino/setup-protoc@v1
      with:
        version: '3.17.3'
    - name: Run go test
      run: go test -v ./...
    - name: Install protoc-gen-pubsub-schema
      run: go install
    - name: Run examples
      run: protoc example/user_add_comment.proto --pubsub-schema_out=.
    - name: Verify examples are working
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git status # Show the files that failed to pass the check.
          exit 1
        fi
